### ISSUE TITLE
ARE U BACK?

### ISSUE THREAD

**Issue by LEGEND-AI** [Hobby-Dev-0/Hobby-Dev-0#4]
Telegram Par Aa Sakte Ho?
Gmail - Krishna045Jaiswal@gmail.com 
WhatsApp- +917255979112

Mujhe New Bot Banana H LEGENDBOT 
BECH DIYA H PAR JISKO BECHA H WO MISSUSE KAR RHA H LEGENDBOT KA

Recover Kar Sakte H Or Mera Telegram Account Delete Kar Diya H Usne

New Account Banaya Hu

T

**Comment by Hobby-Dev-0** [comment]
hmm

**Comment by Hobby-Dev-0** [comment]
I will Help After March

**Comment by LEGEND-AI** [comment]
> I will Help After March

@Hobby-Dev-0 Bro March Khatam hone wala hai
